# Generated by Django 2.2.14 on 2020-09-14 04:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurrConverge',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('草稿', '草稿'), ('发布', '发布'), ('下架', '下架')], default='草稿', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.CharField(default='4c0b79cb98934625a775e4a327433949', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='收敛规则')),
                ('section', models.PositiveSmallIntegerField(default=5, verbose_name='收敛区间')),
                ('count', models.PositiveSmallIntegerField(default=3, verbose_name='收敛阈值')),
                ('filter_args', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='过滤条件')),
            ],
            options={
                'verbose_name': '- 毛刺削峰收敛',
                'verbose_name_plural': '- 毛刺削峰收敛',
            },
        ),
        migrations.CreateModel(
            name='TimeConverge',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('草稿', '草稿'), ('发布', '发布'), ('下架', '下架')], default='草稿', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.CharField(default='4c0b79cb98934625a775e4a327433949', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='开始')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='结束')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '- 固定时间收敛',
                'verbose_name_plural': '- 固定时间收敛',
            },
        ),
        migrations.CreateModel(
            name='DateTimeConverge',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('草稿', '草稿'), ('发布', '发布'), ('下架', '下架')], default='草稿', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.CharField(default='4c0b79cb98934625a775e4a327433949', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='收敛规则')),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, '系统维护'), (1, '休假免扰')], default=0, verbose_name='收敛原因')),
                ('description', models.TextField(blank=True, null=True, verbose_name='规则描述')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '- 日期时间收敛',
                'verbose_name_plural': '- 日期时间收敛',
            },
        ),
    ]
