# 告警事件任务状态

STATUS_NO_RESPONSE = 'NO_RESPONSE'
STATUS_PROCESSING = 'PROCESSING'
STATUS_RESOLVED = 'RESOLVED'
STATUS_REVOKED = 'REVOKED'
STATUS_TIMEOUT = 'TIMEOUT'

# 需要升级的告警状态
STATUS_NEED_UPGRADE = [STATUS_NO_RESPONSE]
