# Generated by Django 2.2.14 on 2020-09-14 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('converge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('NO_RESPONSE', 'NO_RESPONSE'), ('PROCESSING', 'PROCESSING'), ('RESOLVED', 'RESOLVED'), ('REVOKED', 'REVOKED'), ('TIMEOUT', 'TIMEOUT')], default='NO_RESPONSE', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.CharField(default='d1b23d36aa324d6fa7d40c59f5f60f86', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='事件名称')),
                ('host', models.CharField(max_length=128, verbose_name='主机标识')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '警告'), (1, '危险'), (2, '灾难')], default=0, verbose_name='事件级别')),
                ('converge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converge.BurrConverge', verbose_name='毛刺收敛')),
            ],
            options={
                'verbose_name': '- 告警事件',
                'verbose_name_plural': '- 告警事件',
            },
        ),
    ]
