# Generated by Django 2.2.14 on 2020-09-14 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utils.taggit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
        ('message', '__first__'),
        ('taggit', '0004_taggeduuiditem'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_events', to='project.Project', verbose_name='通知级别'),
        ),
        migrations.AddField(
            model_name='event',
            name='messages',
            field=models.ManyToManyField(to='message.Message', verbose_name='关联消息'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='event',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='receive_events', to=settings.AUTH_USER_MODEL, verbose_name='消息接收人'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name=utils.taggit.models.TaggedUUIDItem),
        ),
    ]
